### ISSUE TITLE
Setup a demo site

### ISSUE THREAD

**Issue by rodowi** [CodeandoMexico/reporte-ciudadano#181]
What about setting up a demo instance so visitors can test the project?

Some ideas:
- Mapping NGOs
- Mapping disaster zones
- Reporting bad customer service like [Profeco](http://www.profeco.gob.mx/) (we could add some harvesters to 4SQ and Tw)

**Comment by poguez** [comment]
http://reporte-ciudadano-cmx.herokuapp.com/
